### ISSUE TITLE
Python3 Support in TODO

### ISSUE THREAD

**Issue by KurtPrice** [ExtraHop/DoJobber#1]
Although the TODO states that we need to implement Python3 support, it is still possible to pip install dojobber for python3 and run jobs. The only problem I have noticed seems unrelated and is a complaint that 
** Graphs will not be supported (no dot executable - install graphviz)
** display_graph will not be supported (no display executable - install imagemagick.
This looks like less of a python3 problem and more of an issue with the other dependencies.

**Comment by daethnir** [comment]
If you were to install graphviz and imagemagick packages (e.g. apt-get) then you would find the python3 problems; since the code currently uses external binaries to generate and process the dot output we have a python3 bytes vs string problem.

If you're not installing those then you can't even try to do the graphs so you don't hit the incompatibility.

There are two possible solutions:

* fix the python subprocess invocation (smallest change) or
* use native python dot/display functionality (better change)

**Comment by KurtPrice** [comment]
Is this really a problem with this project though? If it is chosen to keep graphviz and imagemagick this seems more of an issue for those project than DoJobber.

**Comment by daethnir** [comment]
The failure of subprocess to handle the bytes output of dot is absolutely DoJobber's fault.
